// Regenerates src/data/banner.mjs, the block-letter site name used by the
// home terminal, the curl version and the in-page shell. Run: node scripts/banner.mjs
import figlet from 'figlet';
import { writeFileSync } from 'node:fs';

const text = figlet.textSync('gregbishop', { font: 'ANSI Shadow' });
const lines = text.split('\n').map((l) => l.replace(/\s+$/, ''));
while (lines.length && lines[lines.length - 1] === '') lines.pop();
const out = `// Generated by scripts/banner.mjs (figlet, ANSI Shadow). Do not edit by hand.\nexport default ${JSON.stringify(lines.join('\n'))};\n`;
writeFileSync(new URL('../src/data/banner.mjs', import.meta.url), out);
console.log(`banner: ${lines.length} lines, ${Math.max(...lines.map((l) => l.length))} columns`);
